spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/notifications
    username: notifications
    password: notifications
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080